server:
  port: 8769
  
spring:
  application:
    name: zuul
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    api-a: 
      path: /api-a/**
      serviceId: ribbon
    api-b: 
      path: /api-b/**
      serviceId: feign

logging:
  level:
    root: info